name = "GenomicIntersections"
uuid = "73cd4776-3ab0-4d7d-bb6b-cfe6b869bf0a"
authors = ["owensnick <owensnick@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GenomicFeatures = "899a7d2d-5c61-547b-bef9-6698a8d05446"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
GenomicFeatures = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
